### ISSUE TITLE
Accesing local host returns error "The requested resource does not support http method 'GET'."

### ISSUE THREAD

**Issue by pabloderen** [gregorvilkner/Revit2GraphQL#13]
Loading compiling and running the addin from Revit
![image](https://user-images.githubusercontent.com/14131475/89438461-3b798880-d71f-11ea-984e-1e8068c5ba07.png)

Accessing http://localhost:9000/api/graphql/ returns:
Message | "The requested resource does not support http method 'GET'."

Notes: 
- Firewall is open for port 9000
- api/about is returning the information correctly

**Comment by pabloderen** [comment]
Closing it myself, it's not an implementation of graphql viewer but the endpoint. So it only receives Post request

**Comment by gregorvilkner** [comment]
You can do a get on /api/about – that’s the only controller setup for get requests.

No?

**Comment by pabloderen** [comment]
It's working with postman, still need to figure out how to do the queries

**Comment by gregorvilkner** [comment]
You got graphiql, right. It's an excellent electron app to test and explore queries.

https://www.electronjs.org/apps/graphiql

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
